#!/bin/bash

# This file is not part of GNU Emacs.

# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Run a command inside the Vagrant VM in directory /vagrant. See
# HACKING.md

cd $(dirname "$0")
exec vagrant ssh -- cd /vagrant \&\& "$@"

# Local Variables:
# mode: sh-mode
# End:
